version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/app/express-api/
hooks:
  AfterInstall:
    - location: scripts/install_app_dependencies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
